// templates.js — 示例模板库：每个模板就是一段真实的 Sincoding 源码。
// 载入 = 把源码交给引擎解析成积木（与手写文本完全同一条路径，没有第二种真相）。
// 全部用事件函数风格（无 main 无样板），展示"打开就能做出好玩的东西"。
(function (root) {
  root.SIN_TEMPLATES = [
    {
      id: "blank_event",
      name: "空白（事件模式）",
      desc: "当绿旗被点击 + 每一帧，两顶帽子起步",
      icon: "🏁",
      src: [
        '// 当绿旗被点击：做初始化（新建精灵、设初始值）',
        'let hero: int = 0',
        '',
        'fn on_start() {',
        '    hero = sprite_new(0.0, 0.0, 40.0)',
        '}',
        '',
        '// 每一帧：写游戏逻辑（移动、判断、画出精灵）',
        'fn on_frame() {',
        '    sprite_draw(hero)',
        '}',
        '',
      ].join("\n"),
    },
    {
      id: "bounce",
      name: "弹弹球",
      desc: "小球满场反弹，按空格加速",
      icon: "⚽",
      src: [
        '// 弹弹球：碰到边缘就反弹（sprite_bounce）',
        'let ball: int = 0',
        'let speed: float = 5.0',
        '',
        'fn on_start() {',
        '    ball = sprite_new(0.0, 0.0, 36.0)',
        '    sprite_point(ball, 40.0)  // 出发方向',
        '}',
        '',
        'fn on_key_space() {',
        '    speed = speed + 2.0  // 每按一次空格加速',
        '}',
        '',
        'fn on_frame() {',
        '    sprite_move(ball, speed)',
        '    sprite_bounce(ball)',
        '    sprite_draw(ball)',
        '    draw_text("空格=加速", -220.0, 150.0, 18)',
        '}',
        '',
      ].join("\n"),
    },
    {
      id: "catch",
      name: "接金币",
      desc: "左右移动接住下落的金币，10 秒拿高分",
      icon: "🪙",
      src: [
        '// 接金币：←→移动挡板接金币，计时 10 秒',
        'let pad: int = 0',
        'let coin: int = 0',
        'let px: float = 0.0',
        'let cy: float = 160.0',
        'let cx: float = 0.0',
        'let score: int = 0',
        '',
        'fn on_start() {',
        '    pad = sprite_new(0.0, -140.0, 44.0)',
        '    coin = sprite_new(0.0, 160.0, 26.0)',
        '    cx = to_float(random_int(-200, 200))',
        '    timer_reset()',
        '}',
        '',
        'fn on_frame() {',
        '    // 挡板跟着方向键走',
        '    if key_down(key_left()) { px = px - 7.0 }',
        '    if key_down(key_right()) { px = px + 7.0 }',
        '    sprite_move_to(pad, px, -140.0)',
        '    // 金币下落，接住或落地就重来',
        '    cy = cy - 4.0',
        '    sprite_move_to(coin, cx, cy)',
        '    if sprite_touching(pad, coin) {',
        '        score = score + 1',
        '        cy = 160.0',
        '        cx = to_float(random_int(-200, 200))',
        '    }',
        '    if cy < -170.0 {',
        '        cy = 160.0',
        '        cx = to_float(random_int(-200, 200))',
        '    }',
        '    sprite_draw(pad)',
        '    sprite_draw(coin)',
        '    draw_text("分数", -230.0, 150.0, 20)',
        '    draw_number(score, -160.0, 150.0, 20)',
        '    // 10 秒结束',
        '    if timer() > 10.0 {',
        '        draw_text("时间到!", -40.0, 0.0, 30)',
        '    }',
        '}',
        '',
      ].join("\n"),
    },
    {
      id: "spiral",
      name: "画笔螺旋",
      desc: "用画笔画出会转的螺旋",
      icon: "🌀",
      src: [
        '// 画笔螺旋：每帧转一点、走一点，轨迹留在画布上',
        'let pen: int = 0',
        'let step: float = 2.0',
        '',
        'fn on_start() {',
        '    pen = sprite_new(0.0, 0.0, 10.0)',
        '    pen_color(76, 151, 255)',
        '    pen_size(3.0)',
        '}',
        '',
        'fn on_frame() {',
        '    let x0 = sprite_x(pen)',
        '    let y0 = sprite_y(pen)',
        '    sprite_turn(pen, 11.0)',
        '    sprite_move(pen, step)',
        '    pen_line(x0, y0, sprite_x(pen), sprite_y(pen))',
        '    step = step + 0.05',
        '    if step > 9.0 { step = 2.0 }',
        '}',
        '',
      ].join("\n"),
    },
  ];
})(typeof window !== "undefined" ? window : this);
